[theme]

# Primary accent for interactive elements
primaryColor = '#ff0000'

# Background color for the main content area
backgroundColor = '#e6ffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffe6cc'

# Color used for almost all text
textColor = '#4d4d33'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"